[package]
name = "objectTable"
version = "0.0.1"
edition = "2025"

[dependencies]
# git repository
Path = { git = "https://github.com/ln26914/Project11", subdir = "Move_Vector_Hero/vector.move", rev = "framework/testnet" }

[dev-addresses]
sui_test = "0x79deffb469febeb61f0749356e233d6509c234fe9698fa53f11fc2964df5c768"